name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 6 * * *'   # runs every day at 6 AM UTC
  workflow_dispatch:        # allow manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update WakaTime stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_OS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_LOC_CHART: "False"
